language: php
sudo: trues
php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true

install:
  ## back dependencies
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  ## front dependencies
  - . $HOME/.nvm/nvm.sh
  - nvm install node
  - nvm use node
  - node -v
  - npm install

script:
  - vendor/bin/phpunit
  - npm run test
